add_requires("libsdl",{alias="sdl"})
add_requires("imgui")
add_requires("glew")
add_requires("opengl")
add_requires("luajit",{configs = {shared = true}})
add_requires("libgit2", {configs = {shared = true}})
-- add_requires("stb")
-- add_requires("luajit")

target("iiso3")
    set_kind("shared")
    set_arch("x64")
-- add_defines("LUA_BUILD_AS_DLL","LUA_LIB")
    add_files("src/*.cpp")
    -- add_includedirs("imgui/include")
    add_packages("sdl","glew","opengl","imgui","luajit","libgit2")


target("test")
    set_kind("binary")
    add_files("test/main.cpp")
    add_includedirs("src")
    add_packages("sdl","glew","opengl","imgui","luajit")
    add_deps("iiso3")

