add_requires("conan::sdl/2.26.0",{alias="sdl"})
add_requires("conan::imgui/cci.20220621+1.88.docking",{alias="imgui"})
add_requires("conan::glew/2.2.0",{alias="glew"})
add_requires("conan::opengl/system",{alias="opengl"})

target("imgui-impl-sdl-opengl3")
    set_kind("shared")
    add_files("src/*.cpp")
    -- add_includedirs("imgui/include")
    add_packages("sdl","glew","opengl","imgui")

-- target("test")
--     set_kind("binary")
--     add_files("test/main.cpp")
--     add_includedirs("src")
--     add_packages("sdl","glew","opengl","imgui")
--     add_deps("imgui-impl-sdl-opengl3")