name: .NET

on:
  push:
    branches: [ dev ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: |
        cd HoneyBee.Git.Gui/
        dotnet restore
        dotnet build --no-restore -c Release
        cd ../
        ls HoneyBee.Git.Gui/bin/Release/net6.0
    - name: Expose as artifact
      uses: actions/upload-artifact@v2
      with:
        name: HoneyBee-Git-Linux
        path: HoneyBee.Git.Gui/bin/Release/net6.0
        
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: |
        cd HoneyBee.Git.Gui/
        dotnet restore
        dotnet build --no-restore -c Release
        cd ../
        dir HoneyBee.Git.Gui/bin/Release/net6.0
    - name: Expose as artifact
      uses: actions/upload-artifact@v2
      with:
        name: HoneyBee-Git-Windows
        path: HoneyBee.Git.Gui/bin/Release/net6.0
  
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: |
        cd HoneyBee.Git.Gui/
        dotnet restore
        dotnet build --no-restore -c Release
        cd ../
        ls HoneyBee.Git.Gui/bin/Release/net6.0
    - name: Expose as artifact
      uses: actions/upload-artifact@v2
      with:
        name: HoneyBee-Git-Macos
        path: HoneyBee.Git.Gui/bin/Release/net6.0
        
  push-itch:
    runs-on: ubuntu-latest
    needs: [build-windows,build-macos,build-linux]
    steps:
    - name: Download an artifact - linux
      uses: actions/download-artifact@v2
      with:
        name: HoneyBee-Git-Linux
        path: linux/
    - name: Download an artifact - windows
      uses: actions/download-artifact@v2
      with:
        name: HoneyBee-Git-Windows
        path: windows/
    - name: Download an artifact - macos
      uses: actions/download-artifact@v2
      with:
        name: HoneyBee-Git-Macos
        path: macos/

    - name: Check files
      run: |
        ls -alh ./
        ls -alh linux/
        ls -alh windows/
        ls -alh macos/
    
    - name: itch-butler-linux
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: linux
        ITCH_GAME: HoneyBee
        ITCH_USER: wanderer-x
        PACKAGE: linux/
        
    - name: itch-butler-windows
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: windows
        ITCH_GAME: HoneyBee
        ITCH_USER: wanderer-x
        PACKAGE: windows/
    
    - name: itch-butler-osx
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: osx
        ITCH_GAME: HoneyBee
        ITCH_USER: wanderer-x
        PACKAGE: macos/
