name: .NET

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build-ExtractUpdateFiles
      run: |
        cd ExtractUpdateFiles/
        dotnet restore
        dotnet build --no-restore -c Release
        cd ../
        dir ExtractUpdateFiles/bin/Release/net6.0
    - name: Build-HoneyBee.Git.Gui
      run: |
        cd HoneyBee.Git.Gui/
        dotnet restore
        dotnet build --no-restore -c Release
        cd ../
        dir HoneyBee.Git.Gui/bin/Release/net6.0
    - name: Check-Files
      run: |
        dir ExtractUpdateFiles/bin/Release/net6.0
        dir HoneyBee.Git.Gui/bin/Release/net6.0
